name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Rulează workflow-ul când se face push pe branch-ul 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest # Utilizează un runner Ubuntu

    steps:
      - name: Checkout repository # Clonează repository-ul
        uses: actions/checkout@v4 # Folosim v4 pentru cea mai recentă versiune

      - name: Setup Hugo # Configurează Hugo
        uses: peaceiris/actions-hugo@v3 # Folosim v3 pentru cea mai recentă versiune stabilă
        with:
          hugo-version: "0.126.1" # Recomandat să pui o versiune specifică, nu "latest"
          extended: true # Necesită extended pentru unele teme sau funcționalități (ex: SASS)

      - name: Build Hugo site # Construiește site-ul Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages # Rulează acțiunea de deploy
        uses: peaceiris/actions-gh-pages@v4 # Folosim v4 pentru cea mai recentă versiune
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token-ul implicit pentru autentificare
          publish_branch: gh-pages # Branch-ul unde va fi publicat site-ul
          publish_dir: ./public # Directorul care conține fișierele generate de Hugo
          cname: povesti.lejer.ro # Domaniul tău personalizat
          force_orphan: true # Șterge istoricul vechi al branch-ului gh-pages la fiecare deploy
